apiVersion: v1
kind: Namespace
metadata:
  name: madeo07-act3-grupal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: madeo07-act3-grupal
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: cybercharly/madeo07_act3_grupal:nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: madeo07-act3-grupal
spec:
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
